name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            set -e
            cd /var/www/kralbenji.com/public_html
            echo "Running deploy script..."
            chmod +x deploy.sh
            ./deploy.sh

# Default Script (Uncomment for Normal Use)
#         script: |
#             set -e
#             cd /var/www/kralbenji/public_html
#             echo "Running deploy script..."
#             chmod +x deploy.sh
#             ./deploy.sh

# Script with Debugging Commands (Uncomment for Debugging)
# script: |
#   set -e
#   pwd
#   ls -la
#   cd /var/www/kralbenji.com/public_html
#   pwd
#   ls -la
#   chmod +x deploy.sh
#   ./deploy.sh
